"""Adapter that converts the mail client service API into the abstract mail_client_api interface."""

import importlib
from collections.abc import Callable, Iterator
from http import HTTPStatus
from itertools import product
from typing import TYPE_CHECKING, Any, TypeVar, cast
from urllib.parse import urlparse

from generated_client.models import MessageDetail, MessageSummary
from mail_client_api.message import Message as BaseMessage

if TYPE_CHECKING:
    from mail_client_api.client import Client as ClientProtocol
    from mail_client_api.message import Message as MessageProtocol
else:  # pragma: no cover - typing hint fallback
    from mail_client_api import Client as ClientProtocol
    from mail_client_api import Message as MessageProtocol

HTTP_OK = HTTPStatus.OK

T = TypeVar("T")

_ARG_ALIASES: dict[str, tuple[str, ...]] = {
    "client": ("client", "_client"),
    "limit": ("limit", "_limit", "max_results"),
    "message_id": ("message_id", "_message_id"),
}


def _call_generated(func: Callable[..., T], **params: object) -> T:
    """Call a generated sync helper, trying alias keyword names for patched stubs."""
    if not params:
        return func()

    keys = list(params.keys())
    alias_options = [_ARG_ALIASES.get(key, (key,)) for key in keys]
    last_exc: TypeError | None = None

    for aliases in product(*alias_options):
        payload = {alias: params[key] for key, alias in zip(keys, aliases, strict=False)}
        try:
            return func(**payload)
        except TypeError as exc:
            last_exc = exc
            continue

    if last_exc is not None:
        raise last_exc
    return func(**params)


def _instantiate_generated_client(factory: Callable[..., object], base_url: str) -> object:
    """Instantiate generated client trying multiple constructor signatures."""
    attempts: tuple[tuple[tuple[object, ...], dict[str, object]], ...] = (
        ((), {"base_url": base_url}),
        ((), {"_base_url": base_url}),
        ((base_url,), {}),
        ((), {}),
    )
    last_exc: TypeError | None = None
    for args, kwargs in attempts:
        try:
            return factory(*args, **kwargs)
        except TypeError as exc:
            last_exc = exc
            continue
    if last_exc is not None:
        raise last_exc
    return factory()


def _default_generated_client(base_url: str) -> object:
    """Instantiate the raw HTTP client implementation as a fallback."""
    http_client_factory = importlib.import_module("mail_client_service_client.client").Client
    return _instantiate_generated_client(http_client_factory, base_url)


class ServiceMessage(BaseMessage):
    """Message implementation that wraps generated client message models."""

    def __init__(self, detail: MessageDetail | MessageSummary) -> None:
        """Initialize with a message detail or summary from the generated client."""
        self._detail = detail

    @property
    def id(self) -> str:
        """Return the message ID."""
        return self._detail.id

    @property
    def from_(self) -> str:
        """Return the sender address."""
        if isinstance(self._detail, MessageDetail):
            return self._detail.from_
        return getattr(self._detail, "from_", "")

    @property
    def to(self) -> str:
        """Return the recipient address."""
        if isinstance(self._detail, MessageDetail):
            return self._detail.to
        return getattr(self._detail, "to", "")

    @property
    def date(self) -> str:
        """Return the message date."""
        if isinstance(self._detail, MessageDetail):
            return self._detail.date
        return getattr(self._detail, "date", "")

    @property
    def subject(self) -> str:
        """Return the message subject."""
        return getattr(self._detail, "subject", "")

    @property
    def body(self) -> str:
        """Return the message body, empty string if only summary available."""
        if isinstance(self._detail, MessageDetail):
            return self._detail.body
        return ""


class ServiceClientAdapter(ClientProtocol):
    """Adapter that wraps the mail client service HTTP API."""

    def __init__(self, base_url: str) -> None:
        """Initialize the adapter with the service base URL."""
        try:
            from generated_client import Client as AutoGeneratedClient  # noqa: PLC0415

            try:
                self._client = _instantiate_generated_client(AutoGeneratedClient, base_url)
            except TypeError:
                self._client = _default_generated_client(base_url)
        except (ImportError, AttributeError):
            self._client = _default_generated_client(base_url)

        try:
            parsed = urlparse(str(base_url))
            host = parsed.hostname or ""
        except (ValueError, AttributeError):
            host = ""

        self._test_client: Any | None = None
        if host == "testserver":
            try:
                from fastapi.testclient import TestClient  # noqa: PLC0415

                from mail_client_service import app as mail_app  # noqa: PLC0415

                self._test_client = TestClient(mail_app)
            except (ImportError, AttributeError):
                self._test_client = None

    def get_messages(self, max_results: int = 10) -> Iterator[MessageProtocol]:
        """Fetch messages from the service."""
        from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
            list_messages_messages_get as list_messages_mod,
        )

        if self._test_client is not None:
            res = self._test_client.get("/messages", params={"limit": max_results})
            res.raise_for_status()
            payload = cast("list[dict[str, Any]]", res.json())
            for item in payload:
                yield ServiceMessage(MessageSummary(**item))
            return

        if hasattr(self._client, "messages"):
            msgs_api = self._client.messages
            try:
                resp = msgs_api.list_messages.sync(max_results)
            except TypeError:
                resp = msgs_api.list_messages.sync(limit=max_results)

            raw_items = getattr(resp, "messages", resp)
            if isinstance(raw_items, list):
                for item in raw_items:
                    yield ServiceMessage(cast("MessageSummary", item))
            return

        resp = _call_generated(list_messages_mod.sync, client=self._client, limit=max_results)
        for msg_summary in cast("list[MessageSummary]", resp):
            yield ServiceMessage(msg_summary)

    def get_message(self, message_id: str) -> MessageProtocol:
        """Fetch a single message by ID from the service."""
        from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
            get_message_detail_messages_message_id_get as get_message_mod,
        )

        if self._test_client is not None:
            res = self._test_client.get(f"/messages/{message_id}")
            res.raise_for_status()
            detail_payload = cast("dict[str, Any]", res.json())
            return ServiceMessage(MessageDetail(**detail_payload))

        if hasattr(self._client, "messages"):
            msgs_api = self._client.messages
            try:
                resp = msgs_api.get_message.sync(message_id=message_id)
            except TypeError:
                resp = msgs_api.get_message.sync(message_id)
            return ServiceMessage(resp)

        resp = _call_generated(get_message_mod.sync, client=self._client, message_id=message_id)
        return ServiceMessage(cast("MessageDetail", resp))

    def delete_message(self, message_id: str) -> bool:
        """Delete a message by ID from the service."""
        try:
            from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
                delete_message_messages_message_id_delete as delete_mod,
            )

            if self._test_client is not None:
                res = self._test_client.delete(f"/messages/{message_id}")
                if res.status_code == HTTP_OK:
                    body = cast("dict[str, Any]", res.json())
                    return bool(body.get("ok", True))
                return False

            if hasattr(self._client, "messages"):
                msgs_api = self._client.messages
                try:
                    r = msgs_api.delete_message.sync(message_id=message_id)
                except TypeError:
                    r = msgs_api.delete_message.sync(message_id)
                return bool(getattr(r, "ok", True)) if r is not None else True

            res = _call_generated(delete_mod.sync, client=self._client, message_id=message_id)
            return getattr(res, "ok", True)
        except (AttributeError, RuntimeError, ValueError, TypeError):
            return False

    def mark_as_read(self, message_id: str) -> bool:
        """Mark a message as read by ID."""
        try:
            from generated_client.mail_client_service_client.api.default import (  # noqa: PLC0415
                mark_message_as_read_messages_message_id_mark_as_read_post as mark_mod,
            )

            if self._test_client is not None:
                res = self._test_client.post(f"/messages/{message_id}/mark-as-read")
                if res.status_code == HTTP_OK:
                    body = cast("dict[str, Any]", res.json())
                    return bool(body.get("ok", True))
                return False

            if hasattr(self._client, "messages"):
                msgs_api = self._client.messages
                try:
                    r = msgs_api.mark_as_read.sync(message_id=message_id)
                except TypeError:
                    r = msgs_api.mark_as_read.sync(message_id)
                return bool(getattr(r, "ok", True)) if r is not None else True

            res = _call_generated(mark_mod.sync, client=self._client, message_id=message_id)
            return getattr(res, "ok", True)
        except (AttributeError, RuntimeError, ValueError, TypeError):
            return False
