{
 "title": "OSPSD Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "panels": [
  {
   "title": "Success Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(ospsd_requests_success_total[5m])) / sum(rate(ospsd_requests_total[5m]))) * 100",
     "legendFormat": "percent"
    }
   ]
  },
  {
   "title": "Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "(sum(rate(ospsd_requests_failure_total[5m])) / sum(rate(ospsd_requests_total[5m]))) * 100",
     "legendFormat": "percent"
    }
   ]
  },
  {
   "title": "Overall Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(ospsd_request_duration_ms_bucket[5m])) by (le))",
     "legendFormat": "50th quantile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(ospsd_request_duration_ms_bucket[5m])) by (le))",
     "legendFormat": "95th quantile"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(ospsd_request_duration_ms_bucket[5m])) by (le))",
     "legendFormat": "99th quantile"
    }
   ]
  },
  {
   "title": "Avg Latency Per Operation",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg(rate(ospsd_request_duration_ms_sum[5m]) / rate(ospsd_request_duration_ms_count[5m])) by (operation)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Ticket API Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(ospsd_requests_total{operation=\"ticket_create\"}[5m])",
     "legendFormat": "ticket_create"
    },
    {
     "expr": "rate(ospsd_requests_total{operation=\"ticket_list\"}[5m])",
     "legendFormat": "ticket_list"
    },
    {
     "expr": "rate(ospsd_requests_total{operation=\"ticket_get\"}[5m])",
     "legendFormat": "ticket_get"
    },
    {
     "expr": "rate(ospsd_requests_total{operation=\"ticket_update\"}[5m])",
     "legendFormat": "ticket_update"
    },
    {
     "expr": "rate(ospsd_requests_total{operation=\"ticket_delete\"}[5m])",
     "legendFormat": "ticket_update"
    }
   ]
  },
  {
   "title": "AI API Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(ospsd_requests_total{operation=\"ai_generate\"}[5m]))",
     "legendFormat": "ai_generate"
    }
   ]
  }
 ]
}